a=float(input("enter value of a:"))
b=float(input("enter value of b"))
print("*"*50)
print("/t/taddition({},{})={}".format(a,b,a+b))
print("/t/substraction({},{})={}".format(a,b,a-b))
print("/t/tmultiplication({},{})={}".format(a,b,a*b))
print("/t/tdivision({},{})={}".format(a,b,a/b))
print("/t/tfloor division({},{})={}".format(a,b,a//b))
print("/t/tmodulo_division({},{})={}".format(a,b,a%b))
print("/t/t ({} power {})={}".format(a,b,a**b))